/**
 * AIBetNarrative Component
 * Displays AI-generated 1-2 sentence bet hook that affirms our model's pick
 * Reads from Firebase cache generated by GitHub Action
 */

import { useState, useEffect } from 'react';
import { getBetHook } from '../services/perplexityService';
import { TYPOGRAPHY } from '../utils/designSystem';

const AIBetNarrative = ({ game, bestEdge, isMobile }) => {
  const [narrative, setNarrative] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!game) {
      setLoading(false);
      return;
    }

    // Check if we have a positive EV bet
    if (!bestEdge || bestEdge.evPercent <= 0) {
      setLoading(false);
      return;
    }

    const fetchNarrative = async () => {
      try {
        const hook = await getBetHook(game.awayTeam, game.homeTeam);
        setNarrative(hook);
      } catch (error) {
        console.error('Error fetching bet narrative:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchNarrative();
  }, [game?.awayTeam, game?.homeTeam, bestEdge]);

  // Loading state
  if (loading) {
    return (
      <div style={{
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        padding: '1rem',
        fontSize: TYPOGRAPHY.body.size,
        color: 'var(--color-text-muted)',
        fontStyle: 'italic'
      }}>
        <div className="spinner" style={{
          width: '16px',
          height: '16px',
          border: '2px solid rgba(59, 130, 246, 0.3)',
          borderTopColor: '#3B82F6',
          borderRadius: '50%',
          animation: 'spin 0.8s linear infinite'
        }} />
        Generating AI analysis...
      </div>
    );
  }

  // No positive EV bet - show professional message
  if (!bestEdge || bestEdge.evPercent <= 0) {
    return (
      <div style={{
        padding: '1rem',
        fontSize: TYPOGRAPHY.body.size,
        color: 'var(--color-text-muted)',
        lineHeight: '1.6'
      }}>
        This matchup shows balanced odds with no clear edge at current lines. Our model updates continuously as odds shift throughout the day.
      </div>
    );
  }

  // No narrative available yet (still generating)
  if (!narrative) {
    return (
      <div style={{
        padding: '1rem',
        fontSize: TYPOGRAPHY.body.size,
        color: 'var(--color-text-muted)',
        fontStyle: 'italic',
        lineHeight: '1.6'
      }}>
        AI analysis will be available shortly. Our model has identified strong value in this matchup.
      </div>
    );
  }

  // Display narrative
  return (
    <div style={{
      fontSize: TYPOGRAPHY.body.size,
      lineHeight: '1.7',
      color: 'var(--color-text-primary)',
      fontWeight: TYPOGRAPHY.body.weight,
      padding: isMobile ? '0.75rem' : '1rem'
    }}>
      {narrative}
    </div>
  );
};

export default AIBetNarrative;

