/**
 * AIFullStory Component
 * Displays AI-generated 2-3 paragraph deep dive covering primary and alternative bets
 * Reads from Firebase cache generated by GitHub Action
 */

import { useState, useEffect } from 'react';
import { getFullStory } from '../services/perplexityService';
import { TYPOGRAPHY } from '../utils/designSystem';

const AIFullStory = ({ game, bestEdge, isMobile }) => {
  const [story, setStory] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!game || !bestEdge) {
      setLoading(false);
      return;
    }

    const fetchStory = async () => {
      try {
        const fullStory = await getFullStory(game.awayTeam, game.homeTeam);
        setStory(fullStory);
      } catch (error) {
        console.error('Error fetching full story:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchStory();
  }, [game?.awayTeam, game?.homeTeam, bestEdge]);

  // Loading state
  if (loading) {
    return (
      <div style={{
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        padding: isMobile ? '1rem' : '1.5rem',
        fontSize: TYPOGRAPHY.body.size,
        color: 'var(--color-text-muted)',
        fontStyle: 'italic'
      }}>
        <div className="spinner" style={{
          width: '16px',
          height: '16px',
          border: '2px solid rgba(212, 175, 55, 0.3)',
          borderTopColor: '#D4AF37',
          borderRadius: '50%',
          animation: 'spin 0.8s linear infinite'
        }} />
        Generating deep analysis...
      </div>
    );
  }

  // No story available yet
  if (!story) {
    return (
      <div style={{
        padding: isMobile ? '1rem' : '1.5rem',
        fontSize: TYPOGRAPHY.body.size,
        color: 'var(--color-text-muted)',
        fontStyle: 'italic',
        lineHeight: '1.6'
      }}>
        Deep analysis will be available shortly. Check back soon for comprehensive betting insights on both the primary and alternative opportunities in this matchup.
      </div>
    );
  }

  // Split story into paragraphs for better formatting
  const paragraphs = story.split('\n\n').filter(p => p.trim());

  // Display story
  return (
    <div style={{
      padding: isMobile ? '1rem' : '1.5rem'
    }}>
      {paragraphs.map((paragraph, idx) => (
        <p key={idx} style={{
          fontSize: TYPOGRAPHY.body.size,
          lineHeight: '1.7',
          color: 'var(--color-text-primary)',
          fontWeight: TYPOGRAPHY.body.weight,
          marginBottom: idx < paragraphs.length - 1 ? '1rem' : 0
        }}>
          {paragraph}
        </p>
      ))}
    </div>
  );
};

export default AIFullStory;

