import 'dotenv/config';
import admin from 'firebase-admin';
import { readFileSync } from 'fs';
if (!admin.apps.length) admin.initializeApp({ credential: admin.credential.cert(JSON.parse(readFileSync('serviceAccountKey.json', 'utf8'))) });
const db = admin.firestore();
const snap = await db.collection('sharpFlowSpreads').doc('2026-05-09_NBA_okc_lal_spread').get();
const d = snap.data();
console.log('=== TIMESTAMPS ===');
console.log('createTime:        ', snap.createTime?.toDate());
console.log('updateTime:        ', snap.updateTime?.toDate());
console.log('createdAt:         ', d.createdAt ? new Date(d.createdAt) : null);
console.log('lastWriteAt:       ', d.lastWriteAt ? new Date(d.lastWriteAt) : null, '(', Math.round((Date.now()-(d.lastWriteAt||0))/1000), 's ago)');
console.log('lastSyncAt:        ', d.lastSyncAt ? new Date(d.lastSyncAt) : null, '(', Math.round((Date.now()-(d.lastSyncAt||0))/1000), 's ago)');
console.log('closingOddsUpdated:', d.closingOddsUpdatedAt ? new Date(d.closingOddsUpdatedAt) : null);
console.log('lastAction:        ', d.lastAction);
console.log('source:            ', d.source);
console.log('status:            ', d.status);
console.log('sides keys:        ', Object.keys(d.sides || {}));
process.exit(0);
